export default [
    {
      "color-scheme": "light",
      "primary": "#3498db",
      "primary-content": "#ffffff",
      "secondary": "#2ecc71",
      "Accent": "#e67e22",
      "neutral": "#95a5a6",
      "base-100": "#ecf0f1",
      "info": "#1abc9c",
      "success": "#2ecc71",
      "warning": "#f39c12",
      "error": "#e74c3c",
      "theme": "light"
    },
    {
      "color-scheme": "dark",
      "primary": "#09ecf3",
      "primary-content": "#005355",
      "secondary": "#966fb3",
      "Accent": "#ffe999",
      "neutral": "#3b8ac4",
      "base-100": "#345da7",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "oklch(73.95% 0.19 27.33)",
      "theme": "dark"
    },
    {
      "color-scheme": "cupcake",
      "primary": "#fbb6ce",
      "primary-content": "#ffffff",
      "secondary": "#ffecb3",
      "Accent": "#ffe4e1",
      "neutral": "#b6b6b6",
      "base-100": "#fff5f7",
      "info": "#3b82f6",
      "success": "#34d399",
      "warning": "#f59e0b",
      "error": "#ef4444",
      "theme": "cupcake"
    },
    {
      "color-scheme": "bumblebee",
      "primary": "#fcd34d",
      "primary-content": "#3b3b3b",
      "secondary": "#fff7ed",
      "Accent": "#f59e0b",
      "neutral": "#9ca3af",
      "base-100": "#fef9c3",
      "info": "#2563eb",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#f87171",
      "theme": "bumblebee"
    },
    {
      "color-scheme": "emerald",
      "primary": "#10b981",
      "primary-content": "#ffffff",
      "secondary": "#6ee7b7",
      "Accent": "#d1fae5",
      "neutral": "#d1d5db",
      "base-100": "#f3f4f6",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#f87171",
      "theme": "emerald"
    },
    {
      "color-scheme": "corporate",
      "primary": "#0052cc",
      "primary-content": "#ffffff",
      "secondary": "#f4f5f7",
      "Accent": "#deebff",
      "neutral": "#505f79",
      "base-100": "#ffffff",
      "info": "#0065ff",
      "success": "#00c853",
      "warning": "#ffab00",
      "error": "#ff5630",
      "theme": "corporate"
    },
    {
      "color-scheme": "synthwave",
      "primary": "#ff80bf",
      "primary-content": "#ffffff",
      "secondary": "#8dffab",
      "Accent": "#ffd800",
      "neutral": "#1a1a2e",
      "base-100": "#1c1b21",
      "info": "#3b82f6",
      "success": "#22c55e",
      "warning": "#eab308",
      "error": "#ef4444",
      "theme": "synthwave"
    },
    {
      "color-scheme": "retro",
      "primary": "#ef476f",
      "primary-content": "#ffffff",
      "secondary": "#ffd166",
      "Accent": "#06d6a0",
      "neutral": "#26547c",
      "base-100": "#ffe8d6",
      "info": "#219ebc",
      "success": "#06d6a0",
      "warning": "#ff9f1c",
      "error": "#ef476f",
      "theme": "retro"
    },
    {
      "color-scheme": "cyberpunk",
      "primary": "#ff0090",
      "primary-content": "#ffffff",
      "secondary": "#0ff1ce",
      "Accent": "#ffac00",
      "neutral": "#222222",
      "base-100": "#0a0a0a",
      "info": "#00d8ff",
      "success": "#00ff00",
      "warning": "#ffaa00",
      "error": "#ff0044",
      "theme": "cyberpunk"
    },
    {
      "color-scheme": "valentine",
      "primary": "#e85d75",
      "primary-content": "#ffffff",
      "secondary": "#ffcad4",
      "Accent": "#ffc3a0",
      "neutral": "#3f3d56",
      "base-100": "#ffe4e6",
      "info": "#8e8d8f",
      "success": "#f2c6c7",
      "warning": "#e9967a",
      "error": "#c21e56",
      "theme": "valentine"
    },
    {
      "color-scheme": "halloween",
      "primary": "#ff6d00",
      "primary-content": "#000000",
      "secondary": "#ffd700",
      "Accent": "#b82e00",
      "neutral": "#3c3c3c",
      "base-100": "#1c1c1c",
      "info": "#1e90ff",
      "success": "#3cb371",
      "warning": "#ffa500",
      "error": "#ff0000",
      "theme": "halloween"
    },
    {
      "color-scheme": "garden",
      "primary": "#4caf50",
      "primary-content": "#ffffff",
      "secondary": "#ffeb3b",
      "Accent": "#ff9800",
      "neutral": "#c8e6c9",
      "base-100": "#f1f8e9",
      "info": "#2196f3",
      "success": "#4caf50",
      "warning": "#ffeb3b",
      "error": "#f44336",
      "theme": "garden"
    },
    {
      "color-scheme": "forest",
      "primary": "#228b22",
      "primary-content": "#ffffff",
      "secondary": "#6b8e23",
      "Accent": "#b8860b",
      "neutral": "#8b4513",
      "base-100": "#f5f5dc",
      "info": "#4682b4",
      "success": "#32cd32",
      "warning": "#ff8c00",
      "error": "#b22222",
      "theme": "forest"
    },
    {
      "color-scheme": "aqua",
      "primary": "#00ffff",
      "primary-content": "#000000",
      "secondary": "#7fffd4",
      "Accent": "#e0ffff",
      "neutral": "#5f9ea0",
      "base-100": "#f0ffff",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#f87171",
      "theme": "aqua"
    },
    {
      "color-scheme": "lofi",
      "primary": "#808080",
      "primary-content": "#ffffff",
      "secondary": "#c0c0c0",
      "Accent": "#a9a9a9",
      "neutral": "#696969",
      "base-100": "#f0f0f0",
      "info": "#4682b4",
      "success": "#32cd32",
      "warning": "#ffd700",
      "error": "#ff4500",
      "theme": "lofi"
    },
    {
      "color-scheme": "pastel",
      "primary": "#ffb6c1",
      "primary-content": "#000000",
      "secondary": "#ffddc1",
      "Accent": "#ffefd5",
      "neutral": "#d3d3d3",
      "base-100": "#fffaf0",
      "info": "#aec6cf",
      "success": "#77dd77",
      "warning": "#ffb347",
      "error": "#ff6961",
      "theme": "pastel"
    },
    {
      "color-scheme": "fantasy",
      "primary": "#9370db",
      "primary-content": "#ffffff",
      "secondary": "#ffdab9",
      "Accent": "#dda0dd",
      "neutral": "#8a2be2",
      "base-100": "#faf0e6",
      "info": "#6495ed",
      "success": "#7fffd4",
      "warning": "#ff6347",
      "error": "#ff1493",
      "theme": "fantasy"
    },
    {
      "color-scheme": "wireframe",
      "primary": "#d4d4d4",
      "primary-content": "#000000",
      "secondary": "#c0c0c0",
      "Accent": "#a8a8a8",
      "neutral": "#7a7a7a",
      "base-100": "#f7f7f7",
      "info": "#3d3d3d",
      "success": "#7cfc00",
      "warning": "#ffd700",
      "error": "#ff4500",
      "theme": "wireframe"
    },
    {
      "color-scheme": "black",
      "primary": "#000000",
      "primary-content": "#ffffff",
      "secondary": "#1c1c1c",
      "Accent": "#363636",
      "neutral": "#4c4c4c",
      "base-100": "#000000",
      "info": "#ffffff",
      "success": "#00ff00",
      "warning": "#ffff00",
      "error": "#ff0000",
      "theme": "black"
    },
    {
      "color-scheme": "luxury",
      "primary": "#3c3b3d",
      "primary-content": "#ffffff",
      "secondary": "#b5a642",
      "Accent": "#d4af37",
      "neutral": "#000000",
      "base-100": "#f5f5f5",
      "info": "#000080",
      "success": "#8b0000",
      "warning": "#b8860b",
      "error": "#a52a2a",
      "theme": "luxury"
    },
    {
      "color-scheme": "dracula",
      "primary": "#6272a4",
      "primary-content": "#f8f8f2",
      "secondary": "#ff79c6",
      "Accent": "#bd93f9",
      "neutral": "#282a36",
      "base-100": "#44475a",
      "info": "#8be9fd",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555",
      "theme": "dracula"
    },
    {
      "color-scheme": "cmyk",
      "primary": "#00a4e4",
      "primary-content": "#ffffff",
      "secondary": "#ffc300",
      "Accent": "#ff007f",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "info": "#29abe2",
      "success": "#22b573",
      "warning": "#fbb03b",
      "error": "#ed1c24",
      "theme": "cmyk"
    },
    {
      "color-scheme": "autumn",
      "primary": "#d2691e",
      "primary-content": "#ffffff",
      "secondary": "#8b4513",
      "Accent": "#ff8c00",
      "neutral": "#b22222",
      "base-100": "#ffebcd",
      "info": "#4682b4",
      "success": "#32cd32",
      "warning": "#ff4500",
      "error": "#8b0000",
      "theme": "autumn"
    },
    {
      "color-scheme": "business",
      "primary": "#0a0a0a",
      "primary-content": "#ffffff",
      "secondary": "#1a1a1a",
      "Accent": "#333333",
      "neutral": "#4d4d4d",
      "base-100": "#ffffff",
      "info": "#007acc",
      "success": "#4caf50",
      "warning": "#ffc107",
      "error": "#f44336",
      "theme": "business"
    },
    {
      "color-scheme": "acid",
      "primary": "#baff29",
      "primary-content": "#000000",
      "secondary": "#ff00ff",
      "Accent": "#00ff00",
      "neutral": "#ff5722",
      "base-100": "#000000",
      "info": "#3b82f6",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#e11d48",
      "theme": "acid"
    },
    {
      "color-scheme": "lemonade",
      "primary": "#ffefd5",
      "primary-content": "#000000",
      "secondary": "#ffd700",
      "Accent": "#ff69b4",
      "neutral": "#ffffe0",
      "base-100": "#fffacd",
      "info": "#b0e0e6",
      "success": "#00ff7f",
      "warning": "#ff6347",
      "error": "#dc143c",
      "theme": "lemonade"
    },
    {
      "color-scheme": "night",
      "primary": "#1e3a8a",
      "primary-content": "#ffffff",
      "secondary": "#4f46e5",
      "Accent": "#c7d2fe",
      "neutral": "#111827",
      "base-100": "#1f2937",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#fbbf24",
      "error": "#f87171",
      "theme": "night"
    },
    {
      "color-scheme": "coffee",
      "primary": "#6f4e37",
      "primary-content": "#ffffff",
      "secondary": "#d3b8ae",
      "Accent": "#c2b280",
      "neutral": "#b4a08c",
      "base-100": "#e7e4e0",
      "info": "#3b82f6",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#e11d48",
      "theme": "coffee"
    },
    {
      "color-scheme": "winter",
      "primary": "#00bcd4",
      "primary-content": "#ffffff",
      "secondary": "#ffc107",
      "Accent": "#ffeb3b",
      "neutral": "#9e9e9e",
      "base-100": "#f5f5f5",
      "info": "#03a9f4",
      "success": "#4caf50",
      "warning": "#ff9800",
      "error": "#f44336",
      "theme": "winter"
    },
    {
      "color-scheme": "dim",
      "primary": "#374151",
      "primary-content": "#ffffff",
      "secondary": "#4b5563",
      "Accent": "#6b7280",
      "neutral": "#1f2937",
      "base-100": "#111827",
      "info": "#3b82f6",
      "success": "#10b981",
      "warning": "#f59e0b",
      "error": "#e11d48",
      "theme": "dim"
    },
    {
      "color-scheme": "nord",
      "primary": "#88c0d0",
      "primary-content": "#2e3440",
      "secondary": "#81a1c1",
      "Accent": "#a3be8c",
      "neutral": "#4c566a",
      "base-100": "#2e3440",
      "info": "#5e81ac",
      "success": "#a3be8c",
      "warning": "#ebcb8b",
      "error": "#bf616a",
      "theme": "nord"
    },
    {
      "color-scheme": "sunset",
      "primary": "#fd5e53",
      "primary-content": "#ffffff",
      "secondary": "#feb47b",
      "Accent": "#ff7e5f",
      "neutral": "#2a2a72",
      "base-100": "#ffecd2",
      "info": "#f0a500",
      "success": "#ff6f91",
      "warning": "#ffa69e",
      "error": "#ff1e56",
      "theme": "sunset"
    }
  ];
  